name: deploy.yml

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ vps ]

env:
  REGISTRY: ghcr.io
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lower case owner name
        run: |
          echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set lower case owner name
        run: |
          echo "IMAGE_REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Authenticate server with GHCR (Only needed once, or use a PAT)
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Pull the new image
            sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
            
            # Stop and remove the old container
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            
            # Ensure data directory exists
            sudo mkdir -p /opt/linkfixer/data
            sudo chown -R $USER:$USER /opt/linkfixer/data
            
            # Create cookies.txt from secret
            echo "${{ secrets.COOKIES_CONTENT }}" > /opt/linkfixer/data/cookies.txt

            # Run the new version
            sudo docker run -d \
              --name my-app \
              -p 8080:8080 \
              --restart always \
              -v /opt/linkfixer/data:/data \
              -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
              -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              -e BOT_TOKEN_1="${{ secrets.BOT_TOKEN_1 }}" \
              -e BOT_TOKEN_2="${{ secrets.BOT_TOKEN_2 }}" \
              -e GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
              ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}